# Generated by Django 6.0.4 on 2026-05-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='promotion',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='promotion',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='code',
        ),
        migrations.RemoveField(
            model_name='support',
            name='date_publication',
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(choices=[('GC', 'Génie Civil'), ('PG', 'Pétrole et Gaz'), ('INFO', 'Informatique'), ('ARCHI', 'Architecture'), ('ECO', 'Économie'), ('GE', 'Génie Électrique'), ('GM', 'Génie Mécanique')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filiere'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
