# Generated by Django 6.0.4 on 2026-05-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_referencepartagee_salondediscussion_invitationsalon'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='exemples',
            field=models.TextField(blank=True, help_text='Insérez des exemples détaillés, des démonstrations ou des codes sources liés à ce cours.', null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='exercices',
            field=models.TextField(blank=True, help_text="Insérez des énoncés d'exercices ou des questions de révision.", null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='fichier_exercices',
            field=models.FileField(blank=True, help_text="Optionnel : Une fiche de TD ou d'exercices au format PDF", null=True, upload_to='supports/exercices/'),
        ),
        migrations.AlterField(
            model_name='support',
            name='fichier',
            field=models.FileField(help_text='Le cours principal en PDF', upload_to='supports/'),
        ),
    ]
