# Generated by Django 6.0.4 on 2026-05-26 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_support_exemples_support_exercices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='invitationsalon',
            options={'verbose_name': 'Invitation salon', 'verbose_name_plural': 'Invitations salons'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil Étudiant', 'verbose_name_plural': 'Profils Étudiants'},
        ),
        migrations.AlterModelOptions(
            name='referencepartagee',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Ressource partagée', 'verbose_name_plural': 'Ressources partagées'},
        ),
        migrations.AlterModelOptions(
            name='salondediscussion',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Salon de discussion', 'verbose_name_plural': 'Salons de discussion'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['titre'], 'verbose_name': 'Support de cours', 'verbose_name_plural': 'Supports de cours'},
        ),
        migrations.RemoveField(
            model_name='support',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='support',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='support',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationsalon',
            name='accepte',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filiere'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='promotion',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='referencepartagee',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='referencepartagee',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_partagees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencepartagee',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_filieres', to='core.filiere'),
        ),
        migrations.AlterField(
            model_name='referencepartagee',
            name='promotion',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='referencepartagee',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='support',
            name='exemples',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='exercices',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='fichier',
            field=models.FileField(upload_to='supports/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='support',
            name='fichier_exercices',
            field=models.FileField(blank=True, default='', upload_to='supports/exercices/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='invitationsalon',
            unique_together={('salon', 'hote', 'invite', 'accepte')},
        ),
        migrations.CreateModel(
            name='CoursProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], db_index=True, max_length=2)),
                ('intitule', models.CharField(db_index=True, max_length=200)),
                ('code_ue', models.CharField(blank=True, db_index=True, max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_programme', to='core.filiere')),
            ],
            options={
                'verbose_name': 'Cours au programme',
                'verbose_name_plural': 'Cours au programme',
                'ordering': ['promotion', 'intitule'],
                'unique_together': {('filiere', 'promotion', 'intitule')},
            },
        ),
        migrations.AddField(
            model_name='support',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='core.coursprogramme'),
        ),
        migrations.CreateModel(
            name='MessageSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_salons', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_contenus', to='core.salondediscussion')),
            ],
            options={
                'verbose_name': 'Message de salon',
                'verbose_name_plural': 'Messages de salons',
                'ordering': ['date_envoi'],
            },
        ),
    ]
